hw2 done
ok-technopolis-autumn-2022/Ekaterina_Zelenkina pull request #2
Opened 2022-10-24 18:38 UTC by katemewow

##hw2: CSS
###[Ссылка для просмотра](https://celadon-malabi-11c5b4.netlify.app/)

В задании есть неточности, которые пока не удалось пофиксить:
- При наведении только на крестик или на чекбокс часть инпута остается белой;
- Крестик должен исчезать и появляться при наведении;
- Статусы задач должны иметь рамку, когда находятся в фокусе(не реагируют на hover/focus). 

Исправлю в ближайшее время.

2022-10-25 10:07 UTC, fromanywhere requested changes
> Крестик должен исчезать и появляться при наведении;
Еще и на фокус на нем

Так пока что чистенько, жду доработок

2022-10-25 10:07 UTC, fromanywhere commented on style.css
> +    box-shadow: inset 0px -1px 0px #E6E6E6;
лучше бордер, чем тень

2022-10-26 02:02 UTC, katemewow commented
> > Крестик должен исчезать и появляться при наведении;
> > Еще и на фокус на нем
> 
> Так пока что чистенько, жду доработок

2022-10-26 02:07 UTC, katemewow commented
## CSS: fix mistakes
# [Ссылка для просмотра](https://monumental-cuchufli-12e201.netlify.app/)

- Пофикшено появление кнопки удаления;
- При отметке чекбокса текст задачи перечеркивается;
- Добавлено переключение между статусами в футере листа.

2022-10-26 15:51 UTC, fromanywhere requested changes
Почти получилось

2022-10-26 15:51 UTC, fromanywhere commented on style.css
> +    height: 20px;
увеличьте здесь, пожалуйста, зону клика 
<img width="61" alt="image" src="https://user-images.githubusercontent.com/1042969/198071676-af642c27-7ca8-40bc-b8d9-8538e5d5b187.png">

2022-10-26 15:51 UTC, fromanywhere commented on normalize.css
> +    outline: 0;
из-за этого правила у Вас полностью слетает всё accessibility — создатели normalize предполагали, что Вы все фокусы в нужных местах напишете руками

предлагаю его удалить

2022-10-26 15:51 UTC, fromanywhere commented on style.css
> +    opacity: 1;
потерялся стейт на фокус

2022-10-26 15:51 UTC, fromanywhere commented on style.css
> +.status-item3 {
Тут код повторяется трижды, за вычетом ширины
Предлагаю вынести общее под один класс, а от ширины отказаться (она здесь в явном виде не нужна)

2022-10-26 18:32 UTC, katemewow commented on style.css
> +.status-item3 {
Вынесено в общий класс. При попытке убрать ширину ломается логика клика на complete (правая часть не реагирует на клик) и расстояние между элементами (при помощи margin не пофиксить), поэтому оставила решение с width как оптимальное.

2022-10-26 18:32 UTC, katemewow commented
## CSS: fix mistakes
### [Ссылка для просмотра](https://radiant-travesseiro-a932fa.netlify.app/)

- Увеличена зона клика кнопки удаления задачи;
- Из normalize убрано лишнее свойство на фокус;
- Повторяющиеся свойства вынесены в один класс .status-item.

2022-10-27 16:08 UTC, fromanywhere requested changes

2022-10-27 16:08 UTC, fromanywhere commented on style.css
> +    word-break: break-word;
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1042969/198339593-bf3b807f-9305-42cf-8801-23b4b216675a.png">

2022-10-27 16:08 UTC, fromanywhere commented on style.css
> +    border: 1px solid #EBDFDF;
прыгает по горизонтали при переключении

2022-10-27 16:08 UTC, fromanywhere commented on style.css
> +    outline: none;
здесь убит фокус. Кстати, кнопку имеет смысл сделать больше по высоте

2022-10-27 16:08 UTC, fromanywhere commented on style.css
> +    width: 65px;
не самый элегантный способ, но сойдет

2022-10-27 18:16 UTC, katemewow commented
## CSS: fix mistakes
### [Ссылка для просмотра](https://glittering-quokka-40540a.netlify.app/)

- Пофикшены проблемы с длинным текстом таски;
- При переключении статусов позиции элементов не прыгают по горизонтали;
- Увеличена высота кнопки clear, убрано лишнее свойство outline: none;

2022-10-28 09:59 UTC, fromanywhere approved these changes

2022-10-28 10:25 UTC, merged